
package lakshmigowda.session.ejb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SurveyImplementation", targetNamespace = "http://ejb.session.lakshmigowda/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SurveyImplementation {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<lakshmigowda.session.ejb.StudentAppModel>
     * @throws SQLException_Exception
     * @throws ParseException_Exception
     * @throws ClassNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchSurvey", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.SearchSurvey")
    @ResponseWrapper(localName = "searchSurveyResponse", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.SearchSurveyResponse")
    public List<StudentAppModel> searchSurvey(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchAppModel arg0)
        throws ClassNotFoundException_Exception, ParseException_Exception, SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeSurvey", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.StoreSurvey")
    @ResponseWrapper(localName = "storeSurveyResponse", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.StoreSurveyResponse")
    public String storeSurvey(
        @WebParam(name = "arg0", targetNamespace = "")
        StudentAppModel arg0);

    /**
     * 
     * @return
     *     returns java.util.List<lakshmigowda.session.ejb.StudentAppModel>
     * @throws SQLException_Exception
     * @throws ParseException_Exception
     * @throws ClassNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSurveylist", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.GetSurveylist")
    @ResponseWrapper(localName = "getSurveylistResponse", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.GetSurveylistResponse")
    public List<StudentAppModel> getSurveylist()
        throws ClassNotFoundException_Exception, ParseException_Exception, SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteSurvey", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.DeleteSurvey")
    @ResponseWrapper(localName = "deleteSurveyResponse", targetNamespace = "http://ejb.session.lakshmigowda/", className = "lakshmigowda.session.ejb.DeleteSurveyResponse")
    public String deleteSurvey(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
