package lakshmigowda.session.entities;

// Generated Nov 11, 2014 1:30:50 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name = "survey", catalog = "surveys")
public class Survey implements java.io.Serializable {

	private String email;
	private String firstName;
	private String lastName;
	private String streetAddress;
	private String city;
	private String state;
	private String phone;
	private String surveyDate;
	private String likedAboutSchool;
	private String interest;
	private String recommend;
	private String raffle;
	private String comments;

	public Survey() {
	}

	public Survey(String email) {
		this.email = email;
	}

	public Survey(String email, String firstName, String lastName,
			String streetAddress, String city, String state, String phone,
			String surveyDate, String likedAboutSchool, String interest,
			String recommend, String raffle, String comments) {
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.surveyDate = surveyDate;
		this.likedAboutSchool = likedAboutSchool;
		this.interest = interest;
		this.recommend = recommend;
		this.raffle = raffle;
		this.comments = comments;
	}

	@Id
	@Column(name = "email", unique = true, nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "streetAddress", length = 45)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "surveyDate", length = 45)
	public String getSurveyDate() {
		return this.surveyDate;
	}

	public void setSurveyDate(String surveyDate) {
		this.surveyDate = surveyDate;
	}

	@Column(name = "likedAboutSchool", length = 45)
	public String getLikedAboutSchool() {
		return this.likedAboutSchool;
	}

	public void setLikedAboutSchool(String likedAboutSchool) {
		this.likedAboutSchool = likedAboutSchool;
	}

	@Column(name = "interest", length = 45)
	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	@Column(name = "recommend", length = 45)
	public String getRecommend() {
		return this.recommend;
	}

	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}

	@Column(name = "raffle", length = 45)
	public String getRaffle() {
		return this.raffle;
	}

	public void setRaffle(String raffle) {
		this.raffle = raffle;
	}

	@Column(name = "comments", length = 45)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
